server.error.include-message=always
needs.file=data/needs.json
users.file=data/users.json
pledges.file=data/pledges.json
baskets.file=data/baskets.json
logging.level.org.springframework.security=DEBUG
logging.level.com.ufund.api.ufundapi=INFO